module ApplicationCable
  class Connection < ActionCable::Connection::Base
    # Authentication methods generated by authentication generator
    identified_by :current_user
    identified_by :current_bot

    def connect
      Rails.logger.info "[ActionCable] New WebSocket connection attempt"
      Rails.logger.info "[ActionCable] Query string: #{request.query_string}"
      
      # ActionCable stores query parameters in request.query_parameters, not request.params
      sdk_token = request.query_parameters['sdk_token'] || request.params['sdk_token']
      
      # Try bot authentication first (SDK clients)
      if sdk_token.present?
        Rails.logger.info "[ActionCable] Bot authentication attempt with token: #{sdk_token[0...8]}..."
        self.current_bot = Bot.find_by(sdk_token: sdk_token)
        
        if current_bot
          Rails.logger.info "[ActionCable] ✅ Bot authenticated: Bot##{current_bot.id} - #{current_bot.name}"
          self.current_user = nil
        else
          Rails.logger.warn "[ActionCable] ❌ Bot authentication failed: Invalid sdk_token"
          reject_unauthorized_connection
        end
      else
        Rails.logger.info "[ActionCable] User authentication attempt"
        # User authentication (dashboard clients)
        self.current_user = find_verified_user
        self.current_bot = nil
        Rails.logger.info "[ActionCable] ✅ User authenticated: User##{current_user.id}" if current_user
      end
    end

    private

    def find_verified_user
      # Try to authenticate via session token from cookies
      if session_token = cookies.signed[:session_token]
        if session_record = Session.find_by(id: session_token)
          session_record.user
        else
          reject_unauthorized_connection
        end
      # Try to authenticate via Authorization header (for API clients)
      elsif auth_header = request.headers['Authorization']
        token = auth_header.gsub(/Bearer\s+/, '')
        if session_record = Session.find_by(id: token)
          session_record.user
        else
          reject_unauthorized_connection
        end
      else
        reject_unauthorized_connection
      end
    end
    # Authentication methods generated end

    # identified_by :session_id

    # We can access request/cookies object directly here
    # def connect
    #   self.session_id = request.session[:chat_session_id]
    # end
  end
end
