class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
  # Routes for bots generated by controller generator
  resources :bots do
    member do
      get :chat
      delete :unbind_rokid
      get 'SKILL.md', to: 'bots#skill_md', as: :skill_md
      post :generate_skill_token
    end
  end
  # End routes for bots

  # Authentication routes generated by authentication generator
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resource :session, only: [:new, :show, :destroy] do
    get :devices, on: :member
    delete :destroy_one, on: :member
  end
  resources :registrations, only: [:new, :create]
  resource  :password, only: [:edit, :update]

  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"

  resource :invitation, only: [:new, :create]

  # Profile routes
  resource :profile, only: [:show, :edit, :update], controller: 'profiles' do
    member do
      get :edit_password
      patch :update_password
    end
  end

  # Authentication routes generated end

  # write your business logic routes here
  
  # Rokid Lingzhu MCP Integration (Old protocol - deprecated but kept for compatibility)
  # SSE 连接端点
  get 'mcp/rokid/sse', to: 'mcp#sse', as: :rokid_mcp_sse
  # JSON-RPC 2.0 消息处理端点
  post 'messages', to: 'mcp#messages', as: :mcp_messages
  
  # Rokid Lingzhu Platform SSE Integration (New protocol)
  # 灵珠平台自定义智能体 SSE 接口
  post 'sse/rokid', to: 'rokid_sse#sse', as: :rokid_lingzhu_sse

  # API routes
  namespace :api do
    # Rokid Cloudflare Worker API endpoints
    post 'rokid/trigger', to: 'rokid#trigger'
    get 'rokid/poll', to: 'rokid#poll'
    
    namespace :v1 do
      # API authentication routes
      post 'login', to: 'sessions#login'
      delete 'logout', to: 'sessions#destroy'
      post 'sign_up', to: 'registrations#create'
      resource :profile, only: [:show, :update], controller: 'profiles'
      put 'password', to: 'profiles#update_password'

      get 'health', to: 'health#index'
    end
  end

  root 'home#index'

  # Do not write business logic at admin dashboard
  namespace :admin do
    resources :stream_traces
    resources :access_keys
    resources :bots
    resources :users, only: [:index, :show]
    resources :admin_oplogs, only: [:index, :show]
    resources :administrators
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    # Mount GoodJob dashboard
    mount GoodJob::Engine => 'good_job', :constraints => AdminConstraint.new

    root to: 'dashboard#index'
  end

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage')
    }
end
